<?php
require_once __DIR__ . '/../../config/init.php';
if (!has_permission('warehouse.view')) { die('شما مجوز دسترسی به این صفحه را ندارید.'); }

$part_families = find_all($pdo, "SELECT FamilyID, FamilyName FROM tbl_part_families ORDER BY FamilyName");
// --- NEW: Fetch statuses for the new filter ---
$statuses = find_all($pdo, "SELECT StatusID, StatusName FROM tbl_part_statuses ORDER BY StatusName");

$pageTitle = "داشبورد موجودی انبار";
include __DIR__ . '/../../templates/header.php';
?>

<div class="page-header d-flex justify-content-between align-items-center">
    <h1 class="h3 mb-0"><?php echo $pageTitle; ?></h1>
    <a href="index.php" class="btn btn-outline-secondary"><i class="bi bi-arrow-right"></i> بازگشت</a>
</div>

<div id="snapshot-global-feedback"></div>

<div class="card content-card" id="filter-card">
    <div class="card-header"><h5 class="mb-0">فیلتر موجودی</h5></div>
    <div class="card-body">
        <form id="inventory-filter-form">
            <div class="row align-items-end">
                 <div class="col-md-4 mb-3">
                     <label for="family_id" class="form-label">خانواده قطعه (اختیاری)</label>
                     <select class="form-select" id="family_id" name="family_id">
                         <option value="">-- همه خانواده‌ها --</option>
                         <?php foreach ($part_families as $family): ?>
                             <option value="<?php echo $family['FamilyID']; ?>"><?php echo htmlspecialchars($family['FamilyName']); ?></option>
                         <?php endforeach; ?>
                     </select>
                 </div>
                 <div class="col-md-4 mb-3">
                    <label for="part_id" class="form-label">نام قطعه (اختیاری)</label>
                    <select id="part_id" name="part_id" class="form-select" disabled>
                        <option value="">-- همه قطعات خانواده --</option>
                    </select>
                </div>
                 <div class="col-md-4 mb-3">
                    <label for="status_filter_id" class="form-label">وضعیت فعلی (اختیاری)</label>
                    <select id="status_filter_id" name="status_id" class="form-select">
                        <option value="">-- همه وضعیت‌ها --</option>
                        <?php foreach ($statuses as $status): ?>
                            <option value="<?php echo $status['StatusID']; ?>"><?php echo htmlspecialchars($status['StatusName']); ?></option>
                        <?php endforeach; ?>
                         <option value="NULL">-- بدون وضعیت --</option>
                    </select>
                </div>
                <div class="col-md-12 text-end mb-3">
                    <button type="submit" class="btn btn-primary"><i class="bi bi-eye-fill"></i> نمایش موجودی فعلی</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div id="result-container" class="mt-4" style="display:none;">
    <div class="text-center" id="loader"><div class="spinner-border" role="status"></div></div>
    <div class="card content-card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h5 class="mb-0">موجودی فعلی</h5>
            <?php if (has_permission('warehouse.inventory.snapshot')): ?>
            <button type="button" id="record-snapshot-btn" class="btn btn-success btn-sm" disabled>
                <i class="bi bi-camera-fill"></i> ثبت لحظه‌ای موجودی
            </button>
            <?php endif; ?>
        </div>
        <div class="card-body">
            <div id="inventory-result-area">
                <!-- Table will be generated by JS -->
            </div>
             <p id="snapshot-feedback" class="mt-2 small text-muted"></p>
        </div>
    </div>
</div>

<div class="card content-card mt-4">
    <div class="card-header"><h5 class="mb-0">تاریخچه ثبت موجودی</h5></div>
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-striped table-hover table-sm mb-0">
                <thead>
                    <tr>
                        <th class="p-2">تاریخ ثبت</th>
                        <th class="p-2">کاربر</th>
                        <th class="p-2">فیلتر خانواده</th>
                        <th class="p-2">فیلتر قطعه</th>
                        <th class="p-2">فیلتر وضعیت</th>
                        <th class="p-2">عملیات</th>
                    </tr>
                </thead>
                <tbody id="snapshot-history-body">
                    <tr><td colspan="6" class="text-center p-3 text-muted">در حال بارگذاری تاریخچه...</td></tr>
                </tbody>
            </table>
        </div>
    </div>
     <div class="card-footer d-flex justify-content-center" id="snapshot-pagination-container" style="display: none;">
        <nav><ul class="pagination pagination-sm mb-0" id="snapshot-pagination-ul"></ul></nav>
    </div>
</div>

<!-- Snapshot Details Modal -->
<div class="modal fade" id="snapshotDetailsModal" tabindex="-1">
  <div class="modal-dialog modal-lg modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="snapshot-modal-title">جزئیات موجودی ثبت شده</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body" id="snapshotDetailsBody">
        <!-- Content loaded by JS -->
        <div class="text-center p-5"><div class="spinner-border"></div></div>
      </div>
      <div class="modal-footer">
        <!-- Print button added -->
        <button type="button" class="btn btn-secondary" id="print-snapshot-btn"><i class="bi bi-printer"></i> چاپ</button>
        <button type="button" class="btn btn-light" data-bs-dismiss="modal">بستن</button>
      </div>
    </div>
  </div>
</div>
<!-- End Snapshot Details Modal -->

<div class="modal fade" id="deleteSnapshotConfirmModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">تایید حذف</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body">
        آیا از حذف این عکس لحظه‌ای مطمئن هستید؟ این عمل غیرقابل بازگشت است.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" id="confirm-delete-snapshot-btn">بله، حذف کن</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">خیر</button>
        <input type="hidden" id="delete-snapshot-id-input">
      </div>
    </div>
  </div>
</div>

<!-- Print-specific Styles -->
<style>
@media print {
    body * {
        visibility: hidden;
    }
    #snapshotDetailsModal .modal-content,
    #snapshotDetailsModal .modal-body,
    #snapshotDetailsModal .modal-body * {
        visibility: visible;
    }
    #snapshotDetailsModal {
        position: absolute;
        left: 0;
        top: 0;
        margin: 0;
        padding: 0;
        width: 100%;
        height: 100%;
        overflow: visible !important;
        display: block !important; /* Force modal to display */
    }
    #snapshotDetailsModal .modal-dialog {
        width: 100% !important;
        max-width: 100% !important;
        margin: 0 !important;
    }
    #snapshotDetailsModal .modal-content {
        border: none !important;
        box-shadow: none !important;
    }
    #snapshotDetailsModal .modal-header,
    #snapshotDetailsModal .modal-footer {
        display: none !important; /* Hide modal header/footer when printing */
    }
    #snapshotDetailsModal .modal-body {
        padding: 0.5cm !important;
        font-size: 9pt; /* Smaller font for print */
    }
    #snapshot-modal-title-print { /* Use this ID for the printable title */
        visibility: visible;
        display: block;
        font-size: 14pt;
        font-weight: bold;
        text-align: center;
        margin-bottom: 10px;
    }
    #snapshot-modal-filters-print { /* Use this ID for printable filters */
        visibility: visible;
        display: block;
        font-size: 8pt;
        text-align: center;
        color: #555;
        margin-bottom: 15px;
    }
    .table {
        font-size: 8pt !important; /* Smaller table font for print */
    }
    .table th, .table td {
        padding: 4px !important;
        border: 1px solid #ccc !important;
    }
    .table thead th {
        background-color: #f0f0f0 !important;
        -webkit-print-color-adjust: exact;
    }
     .table tfoot td {
        background-color: #f9f9f9 !important;
        -webkit-print-color-adjust: exact;
    }
    .table-primary {
        background-color: #cfe2ff !important; /* Approximate color */
        -webkit-print-color-adjust: exact;
    }
    @page {
        size: A4 portrait;
        margin: 1.5cm;
    }
}
</style>


<?php include __DIR__ . '/../../templates/footer.php'; ?>

<script>
$(document).ready(function() {
    const apiGetCurrentInventoryUrl = '<?php echo BASE_URL; ?>api/api_get_current_inventory.php';
    const apiRecordSnapshotUrl = '<?php echo BASE_URL; ?>api/api_record_inventory_snapshot.php';
    const apiGetSnapshotHistoryUrl = '<?php echo BASE_URL; ?>api/api_get_snapshot_history.php';
    const apiDeleteSnapshotUrl = '<?php echo BASE_URL; ?>api/api_delete_inventory_snapshot.php';
    const familySelect = $('#family_id');
    const partSelect = $('#part_id');
    const statusSelect = $('#status_filter_id'); // New status filter
    const resultContainer = $('#result-container');
    const loader = $('#loader');
    const inventoryResultArea = $('#inventory-result-area');
    const recordSnapshotBtn = $('#record-snapshot-btn');
    const snapshotFeedback = $('#snapshot-feedback');
    const snapshotHistoryBody = $('#snapshot-history-body');
    const snapshotPaginationContainer = $('#snapshot-pagination-container');
    const snapshotPaginationUl = $('#snapshot-pagination-ul');
    const snapshotDetailsModal = $('#snapshotDetailsModal');
    const snapshotDetailsModalBody = $('#snapshotDetailsBody');
    const snapshotModalTitle = $('#snapshot-modal-title');
    const snapshotGlobalFeedback = $('#snapshot-global-feedback'); // For delete success message

    let currentInventoryData = null; // Holds the data fetched for snapshotting
    let currentHistoryPage = 1;

    // --- Family/Part Dropdown Logic ---
    familySelect.on('change', function() {
        const familyId = $(this).val();
        partSelect.prop('disabled', true).html('<option value="">-- همه قطعات خانواده --</option>');
        if (familyId) {
            partSelect.html('<option value="">در حال بارگذاری...</option>');
            $.getJSON('<?php echo BASE_URL; ?>api/api_get_parts_by_family.php', { family_id: familyId })
                .done(function(response) {
                    partSelect.html('<option value="">-- همه قطعات خانواده --</option>');
                    if (response.success && response.data.length > 0) {
                        $.each(response.data, function(i, part) {
                            partSelect.append($('<option>', { value: part.PartID, text: part.PartName }));
                        });
                        partSelect.prop('disabled', false);
                    } else {
                        partSelect.append('<option value="" disabled>قطعه‌ای یافت نشد</option>');
                    }
                })
                .fail(function() { partSelect.html('<option value="">خطا در بارگذاری</option>'); });
        } else { partSelect.html('<option value="">-- ابتدا خانواده را انتخاب کنید --</option>'); }
    });

    // --- Form Submission: Fetch and Display Inventory ---
    $('#inventory-filter-form').on('submit', function(e) {
        e.preventDefault();
        
        resultContainer.show();
        inventoryResultArea.hide(); // Hide result area until data is ready
        loader.show();
        recordSnapshotBtn.prop('disabled', true);
        snapshotFeedback.text('');
        currentInventoryData = null; // Clear previous data

        $.getJSON(apiGetCurrentInventoryUrl, $(this).serialize())
            .done(function(response) {
                loader.hide();
                inventoryResultArea.empty();
                if (response.success && response.data && response.data.length > 0) {
                    currentInventoryData = response.data; // Store full data for snapshot
                    
                    let tableHtml = `<table class="table table-sm table-bordered text-center">
                        <thead><tr class="table-light">
                            <th>قطعه</th>
                            <th>وضعیت خروجی</th>
                            <th>موجودی (KG)</th>
                            <th>موجودی (کارتن)</th>
                        </tr></thead>
                        <tbody>`;
                    let totalsByStatusKG = {};
                    let totalsByStatusCarton = {};
                    let grandTotalKG = 0;
                    let grandTotalCarton = 0;
                    let hasNonZeroBalance = false;

                    response.data.forEach(item => {
                        const statusDisplay = item.StatusName || '-- بدون وضعیت --';
                        const balanceNumKG = parseFloat(item.CurrentBalanceKG);
                        const balanceNumCarton = parseInt(item.CurrentBalanceCarton);
                        
                        if (Math.abs(balanceNumKG) > 0.0001 || Math.abs(balanceNumCarton) > 0) {
                            hasNonZeroBalance = true;
                            tableHtml += `<tr>
                                <td>${item.PartName}</td>
                                <td>${statusDisplay}</td>
                                <td>${balanceNumKG.toFixed(3)}</td>
                                <td>${balanceNumCarton}</td>
                            </tr>`;
                            
                            totalsByStatusKG[statusDisplay] = (totalsByStatusKG[statusDisplay] || 0) + balanceNumKG;
                            grandTotalKG += balanceNumKG;
                            totalsByStatusCarton[statusDisplay] = (totalsByStatusCarton[statusDisplay] || 0) + balanceNumCarton;
                            grandTotalCarton += balanceNumCarton;
                        }
                    });

                    if (!hasNonZeroBalance) {
                        inventoryResultArea.html('<p class="text-center text-muted">موجودی برای فیلتر انتخابی صفر است یا یافت نشد.</p>').show();
                        recordSnapshotBtn.prop('disabled', true);
                        currentInventoryData = null;
                        return;
                    }

                    tableHtml += `</tbody><tfoot class="table-light fw-bold">`;
                    
                    Object.keys(totalsByStatusKG).sort().forEach(status => {
                        if (Math.abs(totalsByStatusKG[status]) > 0.0001) {
                             tableHtml += `<tr>
                                 <td colspan="2" class="text-end pe-3">جمع (KG) وضعیت "${status}":</td>
                                 <td>${totalsByStatusKG[status].toFixed(3)}</td>
                                 <td>-</td>
                             </tr>`;
                        }
                    });
                     tableHtml += `<tr class="table-primary">
                         <td colspan="2" class="text-end pe-3">جمع کل موجودی (KG):</td>
                         <td>${grandTotalKG.toFixed(3)}</td>
                         <td>-</td>
                     </tr>`;

                     Object.keys(totalsByStatusCarton).sort().forEach(status => {
                        if (Math.abs(totalsByStatusCarton[status]) > 0) {
                             tableHtml += `<tr>
                                 <td colspan="2" class="text-end pe-3">جمع (کارتن) وضعیت "${status}":</td>
                                 <td>-</td>
                                 <td>${totalsByStatusCarton[status]}</td>
                             </tr>`;
                        }
                    });
                     tableHtml += `<tr class="table-primary">
                         <td colspan="2" class="text-end pe-3">جمع کل موجودی (کارتن):</td>
                         <td>-</td>
                         <td>${grandTotalCarton}</td>
                     </tr>`;

                     tableHtml += `</tfoot></table>`;
                    inventoryResultArea.html(tableHtml).show();
                    recordSnapshotBtn.prop('disabled', false); // Enable snapshot
                } else if (response.success) {
                    inventoryResultArea.html('<p class="text-center text-muted">موجودی برای فیلتر انتخابی صفر است یا یافت نشد.</p>').show();
                     recordSnapshotBtn.prop('disabled', true);
                     currentInventoryData = null; // Clear data
                } else {
                    inventoryResultArea.html(`<div class="alert alert-danger">${response.message || 'خطا در دریافت اطلاعات.'}</div>`).show();
                     recordSnapshotBtn.prop('disabled', true);
                     currentInventoryData = null;
                }
            })
            .fail(function(jqXHR) {
                 loader.hide();
                 inventoryResultArea.html('<div class="alert alert-danger">خطا در ارتباط با سرور.</div>').show();
                 recordSnapshotBtn.prop('disabled', true);
                 currentInventoryData = null;
                 console.error("AJAX Error:", jqXHR.status, jqXHR.statusText, jqXHR.responseText);
            });
    });

    // --- Record Snapshot Button Logic (Updated) ---
    recordSnapshotBtn.on('click', function() {
        if (!currentInventoryData || currentInventoryData.length === 0) {
            alert('ابتدا موجودی را نمایش دهید یا داده‌ای برای ثبت وجود ندارد.');
            return;
        }
        recordSnapshotBtn.prop('disabled', true).html('<span class="spinner-border spinner-border-sm"></span> ثبت...');
        snapshotFeedback.text('در حال ثبت عکس لحظه‌ای...').removeClass('text-success text-danger').addClass('text-info');

        const snapshotData = {
            family_id: familySelect.val() || null,
            part_id: partSelect.val() || null,
            status_id: statusSelect.val() || null,
            inventory_data: JSON.stringify(currentInventoryData)
        };

        $.post(apiRecordSnapshotUrl, snapshotData)
            .done(function(response) {
                if (response.success) {
                    snapshotFeedback.text(response.message).removeClass('text-info text-danger').addClass('text-success');
                    loadSnapshotHistory(1); // Refresh history starting from page 1
                     setTimeout(() => snapshotFeedback.text(''), 3000); // Clear feedback after 3s
                } else {
                     snapshotFeedback.text(response.message || 'خطا در ثبت.').removeClass('text-info').addClass('text-danger');
                }
            })
            .fail(function(jqXHR) {
                 snapshotFeedback.text('خطای سرور هنگام ثبت.').removeClass('text-info').addClass('text-danger');
                 console.error("Snapshot Record Error:", jqXHR.status, jqXHR.statusText, jqXHR.responseText);
            })
            .always(function() {
                 if (inventoryResultArea.is(':visible') && inventoryResultArea.find('table').length > 0) {
                     recordSnapshotBtn.prop('disabled', false).html('<i class="bi bi-camera-fill"></i> ثبت لحظه‌ای موجودی');
                 } else {
                     recordSnapshotBtn.prop('disabled', true).html('<i class="bi bi-camera-fill"></i> ثبت لحظه‌ای موجودی');
                 }
            });
    });


    // --- Load Snapshot History Function (Updated) ---
    function loadSnapshotHistory(page = 1) {
        currentHistoryPage = page;
        snapshotHistoryBody.html('<tr><td colspan="6" class="text-center p-3 text-muted">در حال بارگذاری...</td></tr>');
        snapshotPaginationContainer.hide();
        snapshotPaginationUl.empty();

        $.getJSON(apiGetSnapshotHistoryUrl, { page: page })
            .done(function(response) {
                snapshotHistoryBody.empty();
                if (response.success && response.data && response.data.length > 0) {
                    response.data.forEach(snap => {
                        const deleteButtonHtml = `
                          <?php if (has_permission('warehouse.inventory.snapshot')): ?>
                            <button class="btn btn-danger btn-sm delete-snapshot-btn py-0 px-1 ms-1"
                                    data-snapshot-id="${snap.SnapshotID}"
                                    data-bs-toggle="modal" data-bs-target="#deleteSnapshotConfirmModal"
                                    title="حذف">
                                <i class="bi bi-trash-fill"></i>
                            </button>
                          <?php endif; ?>`;
                        const row = `<tr>
                            <td class="p-2">${snap.SnapshotTimestampJalali || '-'}</td>
                            <td class="p-2">${snap.RecordedByUsername || '-'}</td>
                            <td class="p-2">${snap.FilterFamilyName || 'همه'}</td>
                            <td class="p-2">${snap.FilterPartName || 'همه'}</td>
                            <td class="p-2">${snap.FilterStatusName || 'همه'}</td>
                            <td class="p-2">
                                <button class="btn btn-info btn-sm view-snapshot-details py-0 px-1"
                                        data-snapshot-id="${snap.SnapshotID}"
                                        data-bs-toggle="modal" data-bs-target="#snapshotDetailsModal"
                                        title="مشاهده جزئیات">
                                    <i class="bi bi-eye-fill"></i>
                                </button>
                                ${deleteButtonHtml}
                            </td>
                        </tr>`;
                        snapshotHistoryBody.append(row);
                    });

                    if (response.pagination && response.pagination.total_pages > 1) {
                        renderPagination(response.pagination.current_page, response.pagination.total_pages);
                        snapshotPaginationContainer.show();
                    }

                } else if (response.success) {
                    snapshotHistoryBody.html('<tr><td colspan="6" class="text-center p-3 text-muted">هیچ سابقه‌ای یافت نشد.</td></tr>');
                } else {
                     snapshotHistoryBody.html(`<tr><td colspan="6" class="text-center p-3 text-warning">${response.message || 'خطا در بارگذاری'}</td></tr>`);
                }
            })
            .fail(function() {
                snapshotHistoryBody.html('<tr><td colspan="6" class="text-center p-3 text-danger">خطا در بارگذاری تاریخچه.</td></tr>');
            });
    }

    // --- Render Pagination Function ---
    function renderPagination(currentPage, totalPages) {
        snapshotPaginationUl.empty();
        const createPageItem = (page, text, isDisabled = false, isActive = false) => {
            const liClass = `page-item ${isDisabled ? 'disabled' : ''} ${isActive ? 'active' : ''}`;
            const link = $('<a>', { class: 'page-link', href: '#', 'data-page': page, text: text });
            return $('<li>', { class: liClass }).append(link);
        };

        snapshotPaginationUl.append(createPageItem(currentPage - 1, 'قبلی', currentPage <= 1));
         if (currentPage > 1) {
            snapshotPaginationUl.append(createPageItem(1, '1'));
            if (currentPage > 3) snapshotPaginationUl.append($('<li>').addClass('page-item disabled').html('<span class="page-link">...</span></li>'));
        }
        if (currentPage > 2) snapshotPaginationUl.append(createPageItem(currentPage - 1, currentPage - 1));
        snapshotPaginationUl.append(createPageItem(currentPage, currentPage, false, true)); // Current page
        if (currentPage < totalPages -1) snapshotPaginationUl.append(createPageItem(currentPage + 1, currentPage + 1));
        if (currentPage < totalPages) {
             if (currentPage < totalPages - 2) snapshotPaginationUl.append($('<li>').addClass('page-item disabled').html('<span class="page-link">...</span></li>'));
             snapshotPaginationUl.append(createPageItem(totalPages, totalPages));
        }
        snapshotPaginationUl.append(createPageItem(currentPage + 1, 'بعدی', currentPage >= totalPages));
    }

     // --- Pagination Click Handler ---
     snapshotPaginationUl.on('click', 'a', function(e) {
        e.preventDefault();
        const page = $(this).data('page');
        if (page && !$(this).parent().hasClass('disabled') && !$(this).parent().hasClass('active')) {
            loadSnapshotHistory(page);
        }
    });

    // --- Snapshot Details Modal Logic (Updated for Print) ---
    $(document).on('click', '.view-snapshot-details', function() {
        const snapshotId = $(this).data('snapshot-id');
        snapshotModalTitle.text('جزئیات موجودی ثبت شده'); // Reset title
        snapshotDetailsModalBody.html('<div class="text-center p-5"><div class="spinner-border"></div></div>');

        $.getJSON(apiGetSnapshotHistoryUrl, { snapshot_id: snapshotId })
            .done(function(response) {
                if (response.success && response.data && response.data.InventoryData) {
                    const snapData = response.data;
                    const inventoryData = JSON.parse(snapData.InventoryData);
                    
                    // --- Create printable header ---
                    let printHeader = `
                        <div id="snapshot-modal-title-print" class="report-title-print">گزارش لحظه‌ای موجودی</div>
                        <div id="snapshot-modal-filters-print" class="text-muted small">
                            <strong>تاریخ ثبت:</strong> ${snapData.SnapshotTimestampJalali} |
                            <strong>کاربر:</strong> ${snapData.RecordedByUsername} |
                            <strong>فیلترها:</strong>
                            خانواده (${snapData.FilterFamilyName || 'همه'}),
                            قطعه (${snapData.FilterPartName || 'همه'}),
                            وضعیت (${snapData.FilterStatusName || 'همه'})
                        </div>`;
                    
                    // --- Create table ---
                    let tableHtml = `<table class="table table-sm table-bordered text-center">
                                         <thead><tr class="table-light">
                                             <th>قطعه</th>
                                             <th>وضعیت خروجی</th>
                                             <th>موجودی (KG)</th>
                                             <th>موجودی (کارتن)</th>
                                         </tr></thead>
                                         <tbody>`;
                    let totalsByStatusKG = {};
                    let totalsByStatusCarton = {};
                    let grandTotalKG = 0;
                    let grandTotalCarton = 0;
                    let hasNonZeroBalanceModal = false;

                    inventoryData.forEach(item => {
                        const statusDisplay = item.StatusName || '-- بدون وضعیت --';
                        const balanceNumKG = parseFloat(item.CurrentBalanceKG);
                        const balanceNumCarton = parseInt(item.CurrentBalanceCarton);
                        
                        if (Math.abs(balanceNumKG) > 0.0001 || Math.abs(balanceNumCarton) > 0) {
                            hasNonZeroBalanceModal = true;
                            tableHtml += `<tr>
                                <td>${item.PartName}</td>
                                <td>${statusDisplay}</td>
                                <td>${balanceNumKG.toFixed(3)}</td>
                                <td>${balanceNumCarton}</td>
                            </tr>`;
                            totalsByStatusKG[statusDisplay] = (totalsByStatusKG[statusDisplay] || 0) + balanceNumKG;
                            grandTotalKG += balanceNumKG;
                            totalsByStatusCarton[statusDisplay] = (totalsByStatusCarton[statusDisplay] || 0) + balanceNumCarton;
                            grandTotalCarton += balanceNumCarton;
                        }
                    });

                     if (!hasNonZeroBalanceModal) {
                          tableHtml += `<tr><td colspan="4" class="text-muted text-center p-3">موجودی ثبت شده برای تمام اقلام صفر بوده است.</td></tr>`;
                     }
                     tableHtml += `</tbody>`;

                     if (hasNonZeroBalanceModal) {
                         tableHtml += `<tfoot class="table-light fw-bold">`;
                         Object.keys(totalsByStatusKG).sort().forEach(status => {
                              if (Math.abs(totalsByStatusKG[status]) > 0.0001) {
                                 tableHtml += `<tr><td colspan="2" class="text-end pe-3">جمع (KG) وضعیت "${status}":</td><td>${totalsByStatusKG[status].toFixed(3)}</td><td>-</td></tr>`;
                              }
                          });
                          tableHtml += `<tr class="table-primary"><td colspan="2" class="text-end pe-3">جمع کل (KG):</td><td>${grandTotalKG.toFixed(3)}</td><td>-</td></tr>`;
                         
                          Object.keys(totalsByStatusCarton).sort().forEach(status => {
                              if (Math.abs(totalsByStatusCarton[status]) > 0) {
                                 tableHtml += `<tr><td colspan="2" class="text-end pe-3">جمع (کارتن) وضعیت "${status}":</td><td>-</td><td>${totalsByStatusCarton[status]}</td></tr>`;
                              }
                          });
                          tableHtml += `<tr class="table-primary"><td colspan="2" class="text-end pe-3">جمع کل (کارتن):</td><td>-</td><td>${grandTotalCarton}</td></tr>`;
                          
                          tableHtml += `</tfoot>`;
                     }
                     tableHtml += `</table>`;
                     
                    // Combine header and table for modal body
                    snapshotDetailsModalBody.html(printHeader + tableHtml);
                    snapshotModalTitle.text(`جزئیات اسنپ‌شات #${snapshotId} (${snapData.SnapshotTimestampJalali})`);
                } else {
                     snapshotDetailsModalBody.html(`<div class="alert alert-warning">${response.message || 'جزئیات یافت نشد.'}</div>`);
                }
            })
            .fail(function() {
                 snapshotDetailsModalBody.html('<div class="alert alert-danger">خطا در دریافت جزئیات.</div>');
            });
    });

    // --- Print Snapshot Modal Logic ---
    $('#print-snapshot-btn').on('click', function() {
        // We just need to trigger the browser's print command.
        // The @media print styles will handle the layout.
        window.print();
    });
    
    // Reset modal body when hidden to ensure spinner shows next time
    snapshotDetailsModal.on('hidden.bs.modal', function () {
         snapshotDetailsModalBody.html('<div class="text-center p-5"><div class="spinner-border"></div></div>');
    });


    // --- Delete Snapshot Logic ---
    let snapshotIdToDelete = null;
    snapshotHistoryBody.on('click', '.delete-snapshot-btn', function() {
        snapshotIdToDelete = $(this).data('snapshot-id');
        $('#delete-snapshot-id-input').val(snapshotIdToDelete);
    });

    $('#confirm-delete-snapshot-btn').on('click', function() {
        snapshotIdToDelete = $('#delete-snapshot-id-input').val();
        if (!snapshotIdToDelete) return;

        const deleteButton = $(this);
        deleteButton.prop('disabled', true).text('در حال حذف...');

        $.post(apiDeleteSnapshotUrl, { snapshot_id: snapshotIdToDelete })
            .done(function(response) {
                 const modalInstance = bootstrap.Modal.getInstance(document.getElementById('deleteSnapshotConfirmModal'));
                 if (modalInstance) modalInstance.hide();
                 snapshotGlobalFeedback.empty(); 

                if (response.success) {
                    snapshotGlobalFeedback.html(`<div class="alert alert-success alert-dismissible fade show" role="alert">${response.message}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>`);
                    loadSnapshotHistory(currentHistoryPage); // Reload current page
                } else {
                    snapshotGlobalFeedback.html(`<div class="alert alert-danger alert-dismissible fade show" role="alert">${response.message || 'خطا در حذف.'}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>`);
                }
                 setTimeout(() => { snapshotGlobalFeedback.find('.alert').alert('close'); }, 5000);

            })
            .fail(function(jqXHR) {
                 const modalInstance = bootstrap.Modal.getInstance(document.getElementById('deleteSnapshotConfirmModal'));
                 if (modalInstance) modalInstance.hide();
                 snapshotGlobalFeedback.empty();
                 snapshotGlobalFeedback.html('<div class="alert alert-danger alert-dismissible fade show" role="alert">خطای سرور هنگام حذف.<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>');
                 console.error("Snapshot Delete Error:", jqXHR.status, jqXHR.statusText, jqXHR.responseText);
                 setTimeout(() => { snapshotGlobalFeedback.find('.alert').alert('close'); }, 5000);
            })
            .always(function() {
                deleteButton.prop('disabled', false).text('بله، حذف کن');
                snapshotIdToDelete = null;
                 $('#delete-snapshot-id-input').val('');
            });
    });

    // --- Initial Load ---
    loadSnapshotHistory(currentHistoryPage);
});
</script>

