<?php
require_once __DIR__ . '/../../config/init.php';
if (!has_permission('warehouse.misc.view')) { die('شما مجوز دسترسی به این صفحه را ندارید.'); }

$employees = find_all($pdo, "SELECT EmployeeID, name FROM tbl_employees ORDER BY name");
$categories = find_all($pdo, "SELECT CategoryID, CategoryName FROM tbl_misc_categories ORDER BY CategoryName");
// Items are loaded dynamically

$pageTitle = "گزارش گردش موجودی متفرقه";
include __DIR__ . '/../../templates/header.php';
?>

<div class="page-header d-flex justify-content-between align-items-center">
    <h1 class="h3 mb-0"><?php echo $pageTitle; ?></h1>
    <a href="misc_index.php" class="btn btn-outline-secondary"><i class="bi bi-arrow-right"></i> بازگشت</a>
</div>

<div class="card content-card" id="filter-card">
    <div class="card-header"><h5 class="mb-0">فیلتر گزارش</h5></div>
    <div class="card-body">
        <form id="filter-form">
            <div class="row align-items-end">
                <div class="col-md-3 mb-3">
                    <label class="form-label">از تاریخ *</label>
                    <input type="text" id="start_date" name="start_date" class="form-control persian-date" required>
                </div>
                <div class="col-md-3 mb-3">
                    <label class="form-label">تا تاریخ *</label>
                    <input type="text" id="end_date" name="end_date" class="form-control persian-date" required>
                </div>
                 <div class="col-md-3 mb-3">
                     <label for="category_id" class="form-label">دسته‌بندی ماده *</label>
                     <select class="form-select" id="category_id" name="category_id" required>
                         <option value="">-- انتخاب کنید --</option>
                         <?php foreach ($categories as $cat): ?>
                             <option value="<?php echo $cat['CategoryID']; ?>"><?php echo htmlspecialchars($cat['CategoryName']); ?></option>
                         <?php endforeach; ?>
                     </select>
                 </div>
                 <div class="col-md-3 mb-3">
                    <label for="item_id" class="form-label">نام ماده (اختیاری)</label>
                    <select id="item_id" name="item_id" class="form-select" disabled>
                        <option value="">-- همه مواد این دسته --</option>
                    </select>
                </div>
                <div class="col-md-12 text-end mb-3">
                    <button type="submit" class="btn btn-primary"><i class="bi bi-search"></i> نمایش گزارش</button>
                    <button type="button" id="print-btn" class="btn btn-secondary"><i class="bi bi-printer"></i> چاپ</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div id="report-container" class="mt-4" style="display:none;">
    <div class="text-center" id="loader"><div class="spinner-border" role="status"><span class="visually-hidden">Loading...</span></div></div>
    <div id="a4-wrapper">
        <div id="report-content" class="a4-page">
            <div id="report-header" class="mb-4 text-center">
                <h2 id="report-main-title" class="report-title-print">گزارش گردش موجودی متفرقه</h2>
                <p id="report-filter-summary" class="text-muted small"></p>
            </div>

            <div id="report-table-container">
                <!-- Tables generated by JS -->
            </div>
        </div>
    </div>
</div>

<style>
/* (استایل‌های چاپ مشابه inventory_report.php) */
#a4-wrapper { background: #525659; padding: 30px 0; }
.a4-page { background: white; width: 21cm; min-height: 29.7cm; display: block; margin: 0 auto; padding: 1.5cm; box-shadow: 0 0 0.5cm rgba(0,0,0,0.5); }
.report-title-print { font-size: 16pt; font-weight: bold; }
.table { font-size: 0.8rem; }
.table th, .table td { padding: 0.3rem 0.5rem; vertical-align: middle; white-space: nowrap;}
.table tfoot td { font-weight: bold;}
.item-report-table { page-break-inside: avoid; margin-bottom: 2rem; }
.item-report-table caption {
    caption-side: top;
    font-size: 1.1rem;
    font-weight: bold;
    color: #000;
    padding: 0.5rem 0;
    border-bottom: 2px solid #000;
}

@media print {
    body * { visibility: hidden; }
    #report-container, #report-container * { visibility: visible; }
    #report-container { position: absolute; left: 0; top: 0; width: 100%; }
    body { background: white !important; margin: 0 !important; padding: 0 !important; }
    .navbar, .page-header, #filter-card, #loader, .btn { display: none !important; visibility: hidden !important; }
    #a4-wrapper { background: white !important; padding: 0 !important; box-shadow: none !important; margin: 0 !important; width: 100% !important; }
    .a4-page { width: 100% !important; height: auto !important; min-height: 0 !important; margin: 0 !important; padding: 1cm !important; box-shadow: none !important; border: none !important; }
    #report-header { display: block !important; visibility: visible !important; margin-bottom: 15px !important; page-break-after: avoid; text-align: center;}
    #report-filter-summary { font-size: 8pt !important; margin-bottom: 5px !important; color: #666 !important; }
    .table { font-size: 8pt !important; margin: 0 0 1.5rem 0 !important; width: 100% !important; table-layout: auto; }
    .table th, .table td { padding: 3px 4px !important; border: 1px solid #ddd !important; white-space: nowrap;}
    .table thead th { background-color: #f0f0f0 !important; -webkit-print-color-adjust: exact !important; font-weight: bold !important; }
    .table tfoot td { background-color: #f8f8f8 !important; -webkit-print-color-adjust: exact !important; font-weight: bold !important; }
    .item-report-table { page-break-inside: avoid !important; }
    .item-report-table caption { font-size: 10pt !important; padding-top: 0.5rem; }
    @page { size: A4 portrait; margin: 1.5cm; }
}
</style>

<?php include __DIR__ . '/../../templates/footer.php'; ?>

<script>
$(document).ready(function() {
    const apiReportUrl = '<?php echo BASE_URL; ?>api/api_misc_get_inventory_report.php';
    const categorySelect = $('#category_id');
    const itemSelect = $('#item_id');

    categorySelect.on('change', function() {
        const categoryId = $(this).val();
        itemSelect.prop('disabled', true).html('<option value="">-- همه مواد این دسته --</option>');
        if (categoryId) {
            itemSelect.html('<option value="">در حال بارگذاری...</option>');
            $.getJSON('<?php echo BASE_URL; ?>api/api_misc_get_items.php', { category_id: categoryId })
                .done(function(response) {
                    itemSelect.html('<option value="">-- همه مواد این دسته --</option>');
                    if (response.success && response.data.length > 0) {
                        response.data.forEach(function(item) {
                            itemSelect.append($('<option>', { value: item.ItemID, text: item.ItemName }));
                        });
                        itemSelect.prop('disabled', false);
                    } else {
                        itemSelect.append('<option value="" disabled>ماده‌ای یافت نشد</option>');
                    }
                })
                .fail(function() { itemSelect.html('<option value="">خطا در بارگذاری</option>'); });
        } else { itemSelect.html('<option value="">-- ابتدا دسته‌بندی --</option>'); }
    });

    $('#filter-form').on('submit', function(e) {
        e.preventDefault();
        const reportContainer = $('#report-container');
        const loader = $('#loader');
        const reportTableContainer = $('#report-table-container');
        const startDate = $('#start_date').val();

        reportContainer.show();
        $('#report-content').hide();
        loader.show();
        reportTableContainer.empty();

        let summary = `خانواده: ${$('#category_id option:selected').text()}`;
        if ($('#item_id').val()) { summary += ` | ماده: ${$('#item_id option:selected').text()}`; }
        summary += ` | بازه: ${startDate} تا ${$('#end_date').val()}`;
        $('#report-filter-summary').text(summary);

        $.getJSON(apiReportUrl, $(this).serialize())
            .done(function(response) {
                if (response.success && response.data && response.data.length > 0) {
                    let allTablesHtml = '';
                    response.data.forEach(itemReport => {
                        let tableHtml = `<table class="table table-sm table-bordered text-center item-report-table" id="report-table-${itemReport.item_name}">
                            <caption>گردش: ${itemReport.item_name} (${itemReport.unit_symbol})</caption>
                            <thead>
                                <tr class="table-light">
                                    <th>تاریخ</th>
                                    <th>نوع تراکنش</th>
                                    <th>عامل</th>
                                    <th>توضیحات</th>
                                    <th>ورود</th>
                                    <th>خروج</th>
                                    <th>مانده</th>
                                </tr>
                            </thead>
                            <tbody>`;
                        
                        // Initial Balance Row
                        tableHtml += `<tr>
                            <td colspan="6" class="text-end pe-3">موجودی اولیه (قبل از ${startDate})</td>
                            <td>${parseFloat(itemReport.initial_balance).toFixed(3)}</td>
                        </tr>`;

                        let currentBalance = parseFloat(itemReport.initial_balance);
                        
                        if (itemReport.transactions && itemReport.transactions.length > 0) {
                            itemReport.transactions.forEach(tx => {
                                // Balance is already calculated as running balance in API
                                tableHtml += `<tr>
                                    <td>${tx.transaction_date_jalali}</td>
                                    <td>${tx.transaction_type_name || '-'}</td>
                                    <td>${tx.operator_name || '-'}</td>
                                    <td>${tx.description || '-'}</td>
                                    <td>${tx.inflow > 0 ? tx.inflow.toFixed(3) : '-'}</td>
                                    <td>${tx.outflow > 0 ? tx.outflow.toFixed(3) : '-'}</td>
                                    <td>${parseFloat(tx.balance).toFixed(3)}</td>
                                </tr>`;
                            });
                        } else {
                            tableHtml += `<tr><td colspan="7" class="text-center text-muted p-3">هیچ تراکنشی در این بازه زمانی یافت نشد.</td></tr>`;
                        }

                        tableHtml += `</tbody>
                            <tfoot class="table-light fw-bold">
                                <tr>
                                     <td colspan="4" class="text-end pe-3">جمع / مانده نهایی:</td>
                                     <td>${parseFloat(itemReport.total_inflow).toFixed(3)}</td>
                                     <td>${parseFloat(itemReport.total_outflow).toFixed(3)}</td>
                                     <td>${parseFloat(itemReport.final_balance).toFixed(3)}</td>
                                 </tr>
                            </tfoot>
                        </table>`;
                        allTablesHtml += tableHtml;
                    }); // end forEach itemReport
                    
                    reportTableContainer.html(allTablesHtml);
                    $('#report-content').show();
                } else if (response.success) {
                    reportTableContainer.html(`<div class="alert alert-warning text-center p-3">هیچ داده‌ای برای فیلتر انتخابی یافت نشد.</div>`);
                    $('#report-content').show();
                } else {
                    reportTableContainer.html(`<div class="alert alert-danger">${response.message || 'خطا در دریافت اطلاعات.'}</div>`);
                    $('#report-content').show();
                }
            })
            .fail(function(jqXHR) {
                 console.error("AJAX Error:", jqXHR.status, jqXHR.statusText, jqXHR.responseText);
                 reportTableContainer.html('<div class="alert alert-danger text-center p-3">خطا در برقراری ارتباط با سرور.</div>');
                 $('#report-content').show();
            })
            .always(function() {
                loader.hide();
            });
    });

    $('#print-btn').on('click', function() {
        if ($('#report-content').is(':hidden')) {
            alert('ابتدا گزارش را ایجاد کنید.');
            return;
        }
        window.print();
    });
});
</script>
